version: "2"
services:
  pottery-backend:
    image: tomcat:8.5.12-jre8
    volumes:
      - ./target/pottery-backend-1.0.0-SNAPSHOT.war:/usr/local/tomcat/webapps/pottery-backend.war
    ports:
      - "8080:8080"


  pottery-db:
    image: postgres:9.6.2
    environment:
      POSTGRES_PASSWORD: pottery
      POSTGRES_USER: pottery
      POSTGRES_DB: pottery
      PGDATA: /pottery-db-data
    volumes:
      - pottery-db:/pottery-db-data:rw
      - ./docs/pg_schema.sql:/docker-entrypoint-initdb.d/pg_schema.sql:ro

volumes:
  pottery-db:
    external: true
